heat_template_version: 2015-10-15

description: |
  #### Development - RCv3

  This stack is running the latest version of
  [Drupal](https://www.drupal.org/),
  [nginx](https://www.nginx.com/),
  and [PHP FPM](http://php-fpm.org/), and
  [MySQL 5.6](http://www.mysql.com/about/).

  **This deployment is meant for development and testing scenarios only and is not
  intended for production use**.

  This template will only function with RackConnect v3.

parameter_groups:
- label: Drupal Settings
  parameters:
  - drupal_url
  - drupal_sitename
  - drupal_user
  - drupal_email
- label: RackConnect Settings
  parameters:
  - rc_network_name
- label: rax-dev-params
  parameters:
  - ansible_source

parameters:
  #Drupal Customization
  drupal_url:
    type: string
    default: example.com
    label: Site Domain
    description: Domain to use with Drupal Site
    constraints:
    - allowed_pattern: "^[a-zA-Z0-9.-]{1,255}.[a-zA-Z]{2,15}$"
      description: Must be a valid domain name
    immutable: true
  drupal_sitename:
    type: string
    default: Example Site
    label: Site Title
    description: Title to use for Drupal Site
    immutable: true
  drupal_user:
    type: string
    default: admin
    label: Drupal Admin Username
    description: Username for Drupal login
    constraints:
    - allowed_pattern: "^[a-zA-Z0-9]*$"
      description: Only can contain A-Z and 0-9
    immutable: true
  drupal_email:
    type: string
    default: admin@example.com
    label: Drupal Admin E-mail
    description: E-mail Address for Drupal Admin User
  rc_network_name:
    type: string
    label: RackConnect Network
    description: Name or UUID of RackConnected network to attach this server to
    constraints:
    - custom_constraint: rackconnect.network
    immutable: true
  #Advanced Options
  server_flavor:
    type: string
    default: 4 GB General Purpose v1
    label: Server Flavor
    description: Flavor of Cloud Server to use
    constraints:
    - allowed_values:
      - 1 GB General Purpose v1
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
    immutable: true
  server_image:
    type: string
    default: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM) (Orchestration)
    label: Server Image
    description: Image to be used for all servers in this stack
    constraints:
    - allowed_values:
      - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM) (Orchestration)
      - CentOS 7 (PVHVM) (Orchestration)
    immutable: true
  ansible_source:
    type: string
    default: http://catalog.rs-heat.com/ansible-roles/ansible-roles.tar.gz
    label: Ansible Tarball
    description: The Ansible Roles will be pulled from the location provided
    immutable: true

resources:
  #Passwords
  root_pass:
    type: OS::Heat::RandomString
  drupal_pass:
    type: OS::Heat::RandomString
  database_pass:
    type: OS::Heat::RandomString
  holland_pass:
    type: OS::Heat::RandomString
  #SSH Key
  ssh_key:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true
  #Software Configurations
  upload_role_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      outputs:
      - name: results
      config:
        str_replace:
          template: |
            #!/bin/bash
            set -e
            mkdir -p /etc/ansible/roles
            wget ansible_source -O /tmp/ansible-roles.tar.gz 2>&1
            tar -xf /tmp/ansible-roles.tar.gz --strip-components=1 -C /etc/ansible/roles
          params:
            ansible_source: { get_param: ansible_source }
  drupal_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      inputs:
      - default: "[]"
        name: firewall_nodes
        type: CommaDelimitedList
      - default: "[]"
        name: firewall_node_rules
        type: CommaDelimitedList
      config: |
        ---
        - name: Install and configure Drupal
          hosts: localhost
          connection: local
          roles:
          - common
          - nginx
          - php-fpm
          - mysql
          - holland
          - composer
          - drupal
          - phpmyadmin
          - firewall
  deploy_roles:
    type: OS::Heat::SoftwareDeployment
    properties:
      signal_transport: TEMP_URL_SIGNAL
      config:
        get_resource: upload_role_config
      server:
        get_resource: drupal_server
  deploy_drupal:
    type: OS::Heat::SoftwareDeployment
    depends_on: deploy_roles
    properties:
      signal_transport: TEMP_URL_SIGNAL
      input_values:
        nginx_vhost_str: { get_param: drupal_url }
        nginx_vhost_template: "drupal"
        nginx_vhost_phpmyadmin: "True"
        mysql_root_password: { get_attr: [root_pass, value] }
        mysql_default_user: "drupal"
        mysql_default_user_password: { get_attr: [database_pass, value ] }
        mysql_default_database: "drupal"
        mysql_dbs:
          - "drupal"
          - "phpmyadmin"
        tz: "America/Chicago"
        holland_mysql_user: "holland"
        holland_mysql_password: {  get_attr: [holland_pass, value] }
        holland_mysql_host: "localhost"
        holland_create_user: "yes"
        drupal_db_host: "localhost"
        drupal_db_name: "drupal"
        drupal_db_user: "drupal"
        drupal_db_password: { get_attr: [database_pass, value] }
        drupal_domain: { get_param: drupal_url }
        drupal_user: { get_param: drupal_user }
        drupal_password: { get_attr: [drupal_pass, value] }
        phpmyadmin_host: "localhost"
        phpmyadmin_user: "root"
        phpmyadmin_pass: { get_attr: [root_pass, value] }
        firewall_global_rules: [ "0.0.0.0,0,22,tcp", "0.0.0.0,0,80,tcp", "0.0.0.0,0,443,tcp"]
        firewall_nodes: []
        firewall_node_rules: []
      config:
        get_resource: drupal_config
      server:
        get_resource: drupal_server
  #Master Server
  drupal_server:
    type: OS::Nova::Server
    properties:
      name: { get_param: "OS::stack_name" }
      image: { get_param: server_image }
      flavor: { get_param: server_flavor }
      key_name: { get_resource: ssh_key }
      software_config_transport: POLL_TEMP_URL
      config_drive: true
      user_data_format: SOFTWARE_CONFIG
      networks:
      - network: { get_param: rc_network_name }
      - network: 11111111-1111-1111-1111-111111111111
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        build_config: "backup_agent_only,monitoring_defaults"
  drupal_server_public_ip:
    type: Rackspace::RackConnect::PublicIP
    depends_on:
    - drupal_server
    properties:
      server_id: { get_resource: drupal_server }

  #Monitoring Checks
  drupal_server_http_check:
    type: Rackspace::CloudMonitoring::Check
    depends_on:
    - deploy_drupal
    - drupal_server_public_ip
    properties:
      entity: { get_resource: drupal_server }
      type: remote.http
      label:
        str_replace:
          template: stack Master HTTP Check
          params:
            stack: { get_param: "OS::stack_name" }
      details:
        url:
          str_replace:
            template: "http://ipaddr"
            params:
              ipaddr: { get_attr: [drupal_server, accessIPv4] }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }
      period: 120
      timeout: 10
      monitoring_zones_poll:
      - Northern Virginia (IAD)
      - Chicago (ORD)
      - Dallas Fort Worth (DFW)
      - London (LON)
      target_hostname: { get_attr: [drupal_server, accessIPv4] }
      target_receiver: IPv4
  #Cloud Backup
  drupal_backup:
    type: Rackspace::Cloud::BackupConfig
    depends_on: drupal_server
    properties:
      #host_ip_address: { get_attr: [drupal_server, networks, private, 0] }
      server: { get_resource: drupal_server }
      BackupConfigurationName:
        str_replace:
          template: stack Weekly Backup
          params:
            stack: { get_param: "OS::stack_name" }
      Inclusions:
      - FilePath: "/var/spool/holland"
        FileItemType: "Folder"
      - FilePath: "/var/www/"
        FileItemType: "Folder"
      NotifyFailure: true
      NotifyRecipients: { get_param: drupal_email }
      TimeZoneId: Central Standard Time
      StartTimeAmPm: AM
      StartTimeHour: 1
      StartTimeMinute: 0
      HourInterval: null
      DayOfWeekId: 0
      Frequency: "Weekly"
      VersionRetention: 30

outputs:
  drupal_login_user:
    description: Drupal Admin User
    value:
      get_param: drupal_user
  drupal_login_password:
    description: Drupal Admin Password
    value:
      get_attr: [drupal_pass, value]
  drupal_public_ip:
    description: Server IP
    value:
      get_attr: [drupal_server, accessIPv4]
  drupal_admin_url:
    description: Drupal Admin URL
    value:
      str_replace:
        template: "https://domain/admin/"
        params:
          domain: { get_param: drupal_url }
  drupal_public_url:
    description: Drupal Public URL
    value:
      str_replace:
        template: "http://domain/"
        params:
          domain: { get_param: drupal_url }
  phpmyadmin_url:
    description: PHPMyAdmin URL
    value:
      str_replace:
        template: "https://IP/phpmyadmin/"
        params:
          IP:
            get_attr: [drupal_server, accessIPv4]
  mysql_user:
    description: Database User
    value: "drupal"
  mysql_password:
    description: Database Password
    value:
      get_attr: [database_pass, value]
  ssh_private_key:
    description: SSH Private Key
    value:
      get_attr: [ssh_key, private_key]
